name: Tests
run-name: üß™ Tests

on:
  # schedule:
   # - cron: '0 8 * * 1,3,5' # PROD will run on weekdays at 10:00 (Kiev TZ) / 06:00 EST
  push:
    branches:
      - template
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the tests against'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
      test_suite:
        description: 'Test suite(s) to run'
        required: true
        default: 'ALL'
        type: choice
        options:
          - chat
          - softserve
          - bookretreats
          - all

# variables https://github.com/cleanchoice/playwright_retreat/settings/variables/actions
env:
  CHAT_E2E_PROD:          ${{vars.CHAT_E2E_PROD}}
  SOFTSERVE_E2E_PROD:     ${{vars.SOFTSERVE_E2E_PROD}}
  BOOKRETREATS_E2E_PROD:  ${{vars.BOOKRETREATS_E2E_PROD}}
  SLACK_CHANNEL:          ${{vars.SLACK_CHANNEL}}
  SLACK_WEBHOOK:          ${{vars.SLACK_WEBHOOK}}
  SLACK_USER:             ${{vars.SLACK_USER}}
  CI_PIPELINE_URL:        "https://github.com/cleanchoice/playwright_retreat/actions/runs/${{github.run_id}}"
  TZ:                     ${{vars.TZ}}
  NODE_VERSION:           22.x

jobs:
  run_prod_tests:
    name: ‚öôÔ∏è Run PROD Tests
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 8 * * 1,3,5' || github.event.inputs.environment == 'prod'
    steps:
    - name: üîé List all environment variables
      run: env | sort

    - name: Checkout
      uses: actions/checkout@v4

    - name: üìó Use node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: üîΩ Install dependencies
      id: install_deps
      run: |
        npm ci
        npx playwright install chrome

    - name: üìù Create .env file
      run: echo "${{secrets.CONFIG_STAGE}}" > .env.stage

    - name: üß™ Run integration tests
      if: steps.install_deps.outcome == 'success' && (github.event_name == 'schedule' || github.event.inputs.test_suite == 'INTEGRATION' || github.event.inputs.test_suite == 'ALL')
      run: xvfb-run npm run $INTEGRATION_STAGE

    run_prod_tests:
    name: ‚öôÔ∏è Run PROD Tests
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 8 * * 1,3,5' || github.event.inputs.environment == 'prod'
    steps:
    - name: üîé List all environment variables
      run: env | sort

    - name: Checkout
      uses: actions/checkout@v4

    - name: üìó Use node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: üîΩ Install dependencies
      id: install_deps
      run: |
        npm ci
        npx playwright install chrome

    - name: üìù Create .env file
      run: echo "${{secrets.CONFIG_PROD}}" > .env.prod

    - name: üß™ Run integration tests
      if: steps.install_deps.outcome == 'success' && (github.event_name == 'schedule' || github.event.inputs.test_suite == 'INTEGRATION' || github.event.inputs.test_suite == 'ALL')
      run: xvfb-run npm run $INTEGRATION_PROD

    - name: ‚öôÔ∏è Run e2e tests
      if: steps.install_deps.outcome == 'success' && (github.event_name == 'schedule' || github.event.inputs.test_suite == 'E2E' || github.event.inputs.test_suite == 'ALL')
      run: xvfb-run npm run $E2E_PROD

  notify_slack_prod:
    name: üö¶ Notify Slack PROD
    runs-on: ubuntu-latest
    needs: [run_prod_tests]
    if: always()
    steps:
    - name: Notify Slack about success
      if: needs.run_prod_tests.result == 'success'
      run: |
        curl -X POST -H 'Content-type: application/json' --data "{\"channel\":\"$SLACK_CHANNEL\",\"username\":\"Github\",\"attachments\":[{\"color\":\"#2EB67D\",\"text\":\":test_tube: :white_check_mark: Pod B PROD tests have succeeded, <$CI_PIPELINE_URL|view logs>\",\"footer\":\"Time: $(TZ=$TZ date)\"}]}" $SLACK_WEBHOOK

    - name: Notify Slack about failure
      if: needs.run_prod_tests.result == 'failure'
      run: |
        curl -X POST -H 'Content-type: application/json' --data "{\"channel\":\"$SLACK_CHANNEL\",\"username\":\"Github\",\"attachments\":[{\"color\":\"#E01E5A\",\"text\":\":test_tube: :x: Pod B PROD tests have failed, <$CI_PIPELINE_URL|view logs>, <$SLACK_USER>\",\"footer\":\"Time: $(TZ=$TZ date)\"}]}" $SLACK_WEBHOOK
