name: Tests
run-name: üß™ Tests

on:
  push:
    branches:
      - template
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the tests against'
        required: true
        default: 'prod'
        type: choice
        options:
          - PROD
      test_suite:
        description: 'Test suite(s) to run'
        required: true
        default: 'ALL'
        type: choice
        options:
          - CHAT_E2E_PROD
          - SOFTSERVE_E2E_PROD
          - BOOKRETREATS_E2E_PROD
          - ALL

# variables https://github.com/cleanchoice/playwright_retreat/settings/variables/actions
env:
  ALL_TESTS_PROD:         ${{vars.ALL_TESTS_PROD}}
  CHAT_E2E_PROD:          ${{vars.CHAT_E2E_PROD}}
  SOFTSERVE_E2E_PROD:     ${{vars.SOFTSERVE_E2E_PROD}}
  BOOKRETREATS_E2E_PROD:  ${{vars.BOOKRETREATS_E2E_PROD}}
  SLACK_CHANNEL:          ${{vars.SLACK_CHANNEL}}
  SLACK_WEBHOOK:          ${{vars.SLACK_WEBHOOK}}
  SLACK_USER:             ${{vars.SLACK_USER}}
  CI_PIPELINE_URL:        "https://github.com/cleanchoice/playwright_retreat/actions/runs/${{github.run_id}}"
  REPORT_URL:             ${{vars.HTML_REPORT_E2E_TESTS_PROD}}
  TZ:                     ${{vars.TZ}}
  NODE_VERSION:           22.x

jobs:
  e2e_tests:
    name: ‚öôÔ∏è E2E tests PROD
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite: [CHAT_E2E_PROD, SOFTSERVE_E2E_PROD, BOOKRETREATS_E2E_PROD]
      fail-fast: false
    steps:
    - name: üîé List all environment variables
      run: env | sort

    - name: Checkout
      uses: actions/checkout@v4

    - name: üìó Use node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: üîΩ Install dependencies
      run: |
        npm install
        npm install -g ts-node
        npx playwright install chrome

    - name: üìù Create .env file
      run: echo "${{secrets.CONFIG_PROD}}" > .env.prod

    - name: ‚öôÔ∏è Run E2E tests
      if: ${{ inputs.test_suite == 'ALL' || inputs.test_suite == matrix.suite }}
      run: xvfb-run npm run ${{ matrix.suite }}

    - name: üìä Prepare HTML Report Directory
      if: always()
      run: |
        echo "Removing existing ${{ matrix.suite }} directory if it exists..."
        rm -rf $GITHUB_WORKSPACE/${{ matrix.suite }}
        
        echo "Creating ${{ matrix.suite }} directory..."
        mkdir -p $GITHUB_WORKSPACE/${{ matrix.suite }}
        
        echo "Current working directory:"
        pwd
        
        echo "Contents of the current working directory:"
        ls -la
        
        echo "Attempting to copy html-report to ${{ matrix.suite }} directory"
        cp -r $GITHUB_WORKSPACE/html-report/* $GITHUB_WORKSPACE/${{ matrix.suite }}/
      shell: bash
    
    - name: üìä Deploy HTML Report
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ matrix.suite }}
        destination_dir: ${{ matrix.suite }}

    - name: Notify Slack about success
      if: success()
      run: |
        curl -X POST -H 'Content-type: application/json' --data "{\"channel\":\"$SLACK_CHANNEL\",\"username\":\"Github\",\"attachments\":[{\"color\":\"#2EB67D\",\"text\":\":test_tube: :white_check_mark: Test suite *${{ matrix.suite }}* has succeeded, :book: <${{ env.CI_PIPELINE_URL }}|VIEW LOGS>, :bar_chart: <${{ env.REPORT_URL }}|VIEW REPORT>\",\"footer\":\"Time: $(TZ=$TZ date)\"}]}" $SLACK_WEBHOOK

    - name: Notify Slack about failure
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' --data "{\"channel\":\"$SLACK_CHANNEL\",\"username\":\"Github\",\"attachments\":[{\"color\":\"#E01E5A\",\"text\":\":test_tube: :x: Test suite *${{ matrix.suite }}* has failed, :book: <${{ env.CI_PIPELINE_URL }}|VIEW LOGS>, :bar_chart: <${{ env.REPORT_URL }}|VIEW REPORT>, <${{ env.SLACK_USER }}>\",\"footer\":\"Time: $(TZ=$TZ date)\"}]}" $SLACK_WEBHOOK

    - name: Notify Slack about cancellation
      if: cancelled()
      run: |
        curl -X POST -H 'Content-type: application/json' --data "{\"channel\":\"$SLACK_CHANNEL\",\"username\":\"Github\",\"attachments\":[{\"color\":\"#808080\",\"text\":\":test_tube: :black_square_for_stop: Test suite *${{ matrix.suite }}* was cancelled, :book: <${{ env.CI_PIPELINE_URL }}|VIEW LOGS>, :bar_chart: <${{ env.REPORT_URL }}|VIEW REPORT>, <${{ env.SLACK_USER }}>\",\"footer\":\"Time: $(TZ=$TZ date)\"}]}" $SLACK_WEBHOOK
